[alias]
format       = "fmt"
format-check = "fmt --check"
lint         = "clippy --locked --all-targets --all-features -- -D warnings"
test-cover   = "llvm-cov --locked --all-features --lcov --output-path lcov.info"
